POST http://localhost:3002/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRpZHppczEiLCJuYW1lIjoiRGlkemlzIFp2YWlnem5lIiwiaWQiOiI2MTQxZWNjMGE4MTdlYzEzYmNjMDFjNWQiLCJpYXQiOjE2MzE3MTA0NzF9.6SaVppkpPL8S-k6ZVYIm7QY_4Jv8LaOEOaqzdn4vyX8

{
    "title": "This is a new blog",
    "author": "valvatti",
    "url": "test.fi",
    "likes": 123
}